export * from './Footer'
export * from './Header'
export * from './Presentation'
export * from './AboutMe'
export * from './Tecnologies'
export * from './Projects'
export * from './TestimonialSlider'
export * from './Contact'